# Generated by Django 5.0.1 on 2024-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='commande',
            name='zipcode',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
