# Generated by Django 5.0.1 on 2024-02-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_commande_email_alter_commande_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='zipcode',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
