# Generated by Django 5.0.1 on 2024-01-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chiffre_Affaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.DecimalField(decimal_places=3, max_digits=12)),
                ('periode', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_supplier', models.CharField(max_length=50)),
                ('date_emprunt', models.DateField()),
                ('Valeur_Dette', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_De_remboursement', models.DateField()),
            ],
        ),
    ]
