# Generated by Django 5.0.1 on 2024-02-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chiffre_Affaire',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='Valeur_Dette',
            new_name='quantite_article',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='date_De_remboursement',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='date_emprunt',
        ),
        migrations.AddField(
            model_name='supplier',
            name='article',
            field=models.CharField(default='Product', max_length=60),
        ),
        migrations.AddField(
            model_name='supplier',
            name='categorie_article',
            field=models.CharField(default='Category', max_length=60),
        ),
        migrations.AddField(
            model_name='supplier',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default='0.99', max_digits=999999999999),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nom_supplier',
            field=models.CharField(default='Supplier', max_length=50),
        ),
    ]
